Match the colorimetry heuristics from mpv
Irrational-Encoding-Wizardry/vs-tools pull request #69
Opened 2023-04-11 07:57 UTC by shssoichiro

The reasoning behind this being that users may experience unexpected differences in color when using this plugin if its heuristics are not the same as the player they are using, and mpv being both open-source and widely used makes it a good candidate to follow.

2023-04-12 13:51 UTC, Setsugennoao requested changes

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> -        if width <= 2048 and height <= 1536:
This seems way too reductive for what we do in VS.

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +        matrix = Matrix.from_video(frame)
You can't use this function here.

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +        primaries = Primaries.from_matrix(matrix)
This looks like a bad idea to me but if it works...

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +        if primaries != Matrix.UNKNOWN:
There's a specific function for this (is_unknown).

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +        if width >= 1280 or height > 576:
Again, too reductive imo.

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> -
Too reductive.

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +    Matrix.BT709: Primaries.BT709
What about the other color matrices?

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +_matrix_primaries_map: dict[Matrix, Primaries] = {
Shouldn't `_primaries_matrix_map` be filled as well?

2023-04-12 13:51 UTC, Setsugennoao commented on vstools/enums/color.py
> +        if height == 576:
Why is this res dependent but Matrix/Transfer isn't?
Even if it's MPV's behaviour, i'd rather not blindly follow it.

2023-04-12 22:10 UTC, shssoichiro commented
If everything mpv does is too reductive then this changeset is meaningless, so I will close it.

2023-04-12 22:10 UTC, closed without merging

2023-04-13 11:22 UTC, Setsugennoao commented
OK!